name: deploy mcv2

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'
          server-id: ossrh
          server-username: ${{ secrets.CENTRAL_TOKEN_USERNAME }}
          server-password: ${{ secrets.CENTRAL_TOKEN_PASSWORD }}
          gpg-private-key: ${{ secrets.GPG_PRIVATE_KEY }}
          gpg-passphrase: ${{ secrets.GPG_PASSPHRASE }}
      - name: Gomasuri
        run: |
          mkdir -p ~/.m2
          echo '<settingsSecurity></settingsSecurity>' > ~/.m2/settings-security.xml
          
      - name: Deploy
        run: mvn -P release -pl :core -am clean deploy -B -U -X
