name: deploy mcv2

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      GPG_PASSPHRASE:  ${{ secrets.GPG_PASSPHRASE }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: debug
        run: echo "${{ secrets.GPG_PRIVATE_KEY }}" | head -20

      - name: Set Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'
          server-id: ossrh
          server-username: ${{ secrets.CENTRAL_TOKEN_USERNAME }}
          server-password: ${{ secrets.CENTRAL_TOKEN_PASSWORD }}

      - name: KeyHatarake
        run: |
          echo "${{ secrets.GPG_PRIVATE_KEY }}" | base64 -d > private.asc
          mkdir -p ~/.gnupg
          chmod 700 ~/.gnupg
          gpg --batch --import private.asc
          gpg --list-secret-keys --keyid-format=long

      - name: Kobiwouru
        run: |
          mkdir -p ~/.m2
          cat <<EOF > ~/.m2/settings.xml
<settings>
  <servers>
    <server>
      <id>ossrh</id>
      <username>${{ secrets.CENTRAL_TOKEN_USERNAME }}</username>
      <password>${{ secrets.CENTRAL_TOKEN_PASSWORD}}</password>
    </server>
  </servers>
</settings>
EOF
          

          
      - name: Deploy
        run: mvn -P release -pl :core -am clean deploy -B -U -X -Dgpg.passphrase="${{ secrets.GPG_PASSPHRASE }}"
