name: Deploy MC
on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Import key
        run: echo "${{ secrets.GPG_PRIVATE_KEY }}" | base64 -d | gpg --batch --import


      - name: debugf cli pom
        run: |
          echo "Tell Debug"
          cat cli/pom.xml
      - name: Set Java
        uses: actions/setup-java@v4
        with:
           distribution: temurin
           java-version: '21'

      - name: Deploy
        run:  mvn -B -P release clean deploy -Dgpg.passphrase="${{ secrets.GPG_PASSPHRASE }}" -Dcentral.sonatype.username="${{ secrets.CENTRAL_TOKEN_USERNAME }}" -Dcentral.sonatype.password="${{ secrets.CENTRAL_TOKEN_PASSWORD }}"

      