name: Deploy MC
on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Import GPG key
        run: echo "${{ secrets.GPG_PRIVATE_KEY }}" | base64 -d | gpg --batch --import

      # ✅ server-idなどの認証設定を完全に削除します
      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Build and Deploy to Central
        # ✅ -D オプションで直接ユーザー名とパスワードを指定する、最も確実な方式です
        run: >
          mvn -B -P release clean deploy
          -Dgpg.passphrase="${{ secrets.GPG_PASSPHRASE }}"
          -Dcentral.sonatype.username="${{ secrets.CENTRAL_TOKEN_USERNAME }}"
          -Dcentral.sonatype.password="${{ secrets.CENTRAL_TOKEN_PASSWORD }}"