name: Deploy MC
on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Import key
        run: echo "${{ secrets.GPG_PRIVATE_KEY }}" | base64 -d | gpg --batch --import

      - name: Debug Keys
        run: |
          if [ -z "${{ secrets.CENTRAL_TOKEN_USERNAME}}" ]; then 
            echo "::error::CENTRAL_TOKEN_USERNAME secrets is not set"
          else 
            echo "CENTRAL_USERNAME Set"
          fi
          if [ -z "${{ secrets.CENTRAL_TOKEN_PASSWORD}}" ]; then
            echo "::error::CENTRAL_TOKEN_PASSWORD not set"
          else 
            echo "CENTRAL_TOKEN_PASSWORD set"
          fi


      - name: Set Java
        uses: actions/setup-java@v4
        with:
           distribution: temurin
           java-version: '21'
           server-id: central
           server-username: ${{ secrets.CENTRAL_TOKEN_USERNAME }}
           server-password: ${{ secrets.CENTRAL_TOKEN_PASSWORD }}


      - name: Deploy
        run: |
           mvn -B -P releasemvc clean install -D gpg.passphrase="${{ secrets.GPG_PASSPHRASE }}"

           mvn -B -X -pl core -P releasemvc deploy \
            -D gpg.passphrase="${{ secrets.GPG_PASSPHRASE}}" \
            -D central.sonatype.username="${{ secrets.CENTRAL_TOKEN_USERNAME }}" \
            -D central.sonatype.password="${{ secrets.CENTRAL_TOKEN_PASSWORD}}"

      