name: MavenCentral
on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: JavaSet
        uses: actions/setup-java@v4

        with:
          distribution: temurin
          java-version: 21
          server-id: ossrh
          gpg-private-key: ${{ secrets.GPG_PRIVATE_KEY }}
          gpg-passphrase: ${{ secrets.GPG_PASSPHRASE }}
          server-username: ${{ secrets.OSSRH_USERNAME }}
          server-passphrase: ${{ secrets.OSSRH_PASSWORD }}


      - name: deploy
        run: mvn -pl :core -am clean deploy -B -U

          
