name: build jpackage Windows 

on:
  workflow_dispatch:

jobs:
  package-windows:
    runs-on: windows-latest

    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: Java 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 21

      - name: build
        run: |
          mvn clean package 
          
      - name: Package Win
        shell: cmd
        run: |
          jpackage ^
          --type exe ^
          --input cli/target ^
          --dest out ^
          --name SdhjChecker ^
          --main-jar cli-flat.jar ^
          --main-class io.github.harutkue.checker.cli.app.Main ^
          --win-console

      - name: package Upload
        uses: actions/upload-artifact@v4
        with:
          name: SdhjChecker-exe
          path: out/*.exe
