name: build jpackage Linux 

on:
  workflow_dispatch:

jobs:
  package-linux:
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: Java 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
          
      - name: fakeroot Install
        run: |
          sudo apt-get update
          sudo apt-get install -y fakeroot libfuse2

      - name: build
        run: | 
          mvn clean package 
          
      - name: Package Linux
        run: |
          jpackage \
          --type deb \
          --input cli/target \
          --dest out \
          --name SdhjChecker \
          --main-jar cli-flat.jar \
          --main-class io.github.harutkue.checker.cli.app.Main \
      
      - name: package Upload
        uses: actions/upload-artifact@v4
        with:
          name: SdhjChecker-deb
          path: out/*.deb
